# Model Arguments
model_name_or_path: "meta-llama/Llama-3.1-8B" # (base model)
trust_remote_code: True
device_map: "cuda"

# Data Arguments
dataset_name: "saiteki-kai/Beavertails-it"
config_name: "multilingual"
train_split: "330k_train"
test_split: "330k_test"
eval_split_ratio: 0.1
max_seq_length: 1024
pad_to_max_length: False

# Training Arguments
seed: 42
run_name: "QA-Llama-3.1"
output_dir: "output/QA-Llama-3.1"
report_to: "wandb"
log_level: "info"
bf16: True
tf32: True
deepspeed: configs/deepspeed_zero2.json
ddp_find_unused_parameters: False
use_liger_kernel: True
gradient_checkpointing: True
gradient_checkpointing_kwargs:
  use_reentrant: False
group_by_length: True
num_train_epochs: 10
per_device_train_batch_size: 32
per_device_eval_batch_size: 16
gradient_accumulation_steps: 1
warmup_ratio: 0.1
weight_decay: 0.0005
learning_rate: 0.00005
lr_scheduler_type: "cosine"
eval_strategy: "epoch"
save_strategy: "best"
logging_steps: 10
metric_for_best_model: "eval_micro_f1"
load_best_model_at_end: True
save_total_limit: 1
push_to_hub: True
