# Model Arguments
model_name_or_path: "meta-llama/Llama-Guard-3-8B"
trust_remote_code: True
device_map: "cuda"
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_modules: all-linear
completion_only: true

# Data Arguments
dataset_name: "saiteki-kai/Beavertails-it"
config_name: "multilingual"
train_split: "330k_train"
test_split: "330k_test"
eval_split_ratio: 0.1
pad_to_max_length: False
include_descriptions: false

# Training Arguments
seed: 42
run_name: "QA-Llama-Guard-3-8B"
output_dir: "output/QA-Llama-Guard-3-8B"
report_to: "wandb"
log_level: "info"
bf16: True
tf32: True
ddp_find_unused_parameters: False
use_liger: true
use_liger_kernel: True
gradient_checkpointing: True
gradient_checkpointing_kwargs:
  use_reentrant: False
group_by_length: True
num_train_epochs: 3
per_device_train_batch_size: 32
per_device_eval_batch_size: 16
gradient_accumulation_steps: 1
warmup_ratio: 0.1
weight_decay: 0.0005
learning_rate: 0.00005
lr_scheduler_type: "cosine"
eval_strategy: "epoch"
save_strategy: "best"
logging_steps: 10
metric_for_best_model: "eval_micro_f1"
load_best_model_at_end: True
save_total_limit: 1
push_to_hub: True
