# Model Arguments
model_name_or_path: "microsoft/deberta-v3-large"
cls_dropout: 0.2
trust_remote_code: True
device_map: "cuda"

# Data Arguments
dataset_name: "saiteki-kai/Beavertails-it"
config_name: "multilingual"
train_split: "330k_train"
test_split: "330k_test"
eval_split_ratio: 0.1
max_seq_length: 520
pad_to_max_length: False
template: "{question} {answer}"
tune_thresholds: True

# Training Arguments
seed: 42
run_name: "QA-DeBERTa-v3-large-threshold-v2"
output_dir: "output/QA-DeBERTa-v3-large-threshold-v2"
report_to: "wandb"
log_level: "info"
bf16: True
tf32: True
dataloader_num_workers: 8
ddp_find_unused_parameters: False
use_liger_kernel: True
gradient_checkpointing: True
gradient_checkpointing_kwargs:
  use_reentrant: False
group_by_length: True
num_train_epochs: 10
per_device_train_batch_size: 32
per_device_eval_batch_size: 64
gradient_accumulation_steps: 2
warmup_ratio: 0.03
weight_decay: 0.01
learning_rate: 0.00001
lr_scheduler_type: "cosine"
eval_strategy: "epoch"
save_strategy: "epoch"
logging_steps: 10
metric_for_best_model: "eval_micro_f1"
load_best_model_at_end: True
save_total_limit: 1
push_to_hub: True
