[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "moderation"
version = "0.0.1"
description = "QA moderation for Beavertails"
readme = "README.md"
authors = [{ name = "Giuseppe Magazzù", email = "giuseppe.magazu@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.11.0",
    "datasets>=4.4.1",
    "deepspeed>=0.18.2",
    "determined>=0.37.0",
    "hf-xet>=1.2.0",
    "huggingface-hub[hf-xet]>=0.36.0",
    "liger-kernel>=0.6.3",
    "peft>=0.18.0",
    "scikit-learn>=1.7.2",
    "sentencepiece>=0.2.1",
    "tiktoken>=0.12.0",
    "torch>=2.9.1",
    "transformers>=4.57.1",
    "trl>=0.25.1",
    "wandb>=0.23.0",
]

[tool.ruff]
line-length = 120
fix = true
show-fixes = true

[tool.ruff.lint]
select = [
    #"ERA",
    "ANN",
    "S",
    "A",
    #"D",
    "C4",
    "EM",
    "ICN",
    "LOG",
    "G",
    "INP",
    "PIE",
    "PYI",
    "Q",
    "RET",
    "SLF",
    "SIM",
    "TID",
    "TC",
    "I",
    "ARG",
    "PTH",
    "NPY",
    "PD",
    "N",
    "PERF",
    "E",
    "W",
    "F",
    "RUF",
    "TRY",
]
ignore = ["N806", "D100", "D104", "ANN401"]

[tool.ruff.lint.per-file-ignores]
"scripts/*" = ["INP001"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
lines-after-imports = 2
lines-between-types = 1
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true

[dependency-groups]
dev = [
    "pre-commit>=4.4.0",
    "ruff>=0.14.5",
    "seaborn>=0.13.2",
]
